---
encoding: utf-8
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - bin
  - CNAME
  - lib
  - tmp
  - vendor
kramdown:
  input: GFM
  gfm_quirks: paragraph_end
  parse_block_html: true
defaults:
  -
    values:
      layout: "default"
